server:
  port: 8081

spring:
  application:
    name: business-person-v1
  r2dbc:
    url: r2dbc:mysql://localhost:3306/person_db?useSSL=true&serverTimezone=America/Lima
    username: root
    password: farro123
    pool:
      max-size: 10
      max-idle-time: 10000
      max-life-time: 30000
      max-create-connection-time: 20000